### ISSUE TITLE
Botão de imprimir boleto nao aparece na finalizacao

### ISSUE THREAD

**Issue by magnored** [gerencianet/magento-dev#1]
Ola a todos

Gostaria de saber o que acontece pois na finalizacao do pedido nao aparece o botao para o cliente imprimir o boleto.
Contudo, é enviado o email com todas informações corretas.

Acredito que seja algo no link de finalizacao da minha loja que aponta para http://www.site.com.br/checkout/onepage/success/

**Comment by tavinus** [comment]
Também estou com o mesmo problema.
Ao finalizar o pedido não há botão para imprimir o boleto.
Mas o e-mail da gerencianet com a cobrança vai sem problemas.
Estou usando o onepage do Magento CE 1.9.1 com PHP 5.4.
Alguma idéia de como ter o botão do boleto no checkout e na página do pedido (para reimprimir?)
Ah sim, só testei no modo desenvolvimento até agora..

**Comment by ceciliadeveza** [comment]
Prezados @magnored e @tavinus,

Por favor, verifiquem se as permissões estão setadas corretamente, dessa forma:

– 755 para todos os diretórios
– 644 para todos os arquivos
– 777 para app/etc/, var/ e media/

ou:

sudo find . -type d -exec chmod 755 {} \;
sudo find . -type f -exec chmod 644 {} \;
sudo chmod 777 -R app/etc/;
sudo chmod 777 -R var/;
sudo chmod 777 -R media/;

**Comment by tavinus** [comment]
Olá @ceciliadeveza, obrigado pela resposta.
Eu mudei as permissões conforme recomendado, limpei a cache do Magento e testei de novo e nada mudou.

![screen shot 2016-03-16 at 6 53 51 pm](https://cloud.githubusercontent.com/assets/8039413/13829960/9a0afee0-eba8-11e5-937f-cbcda6f82f33.png)

Também me parece meio perigoso ter permissão 777 em algumas pastas e arquivos (e isso não resolve o problema).

Outras infos:
- Tem o Inovarti one step checkout instalado.
- Vou testar sem ele, mas hoje a tarde quando tentei a API saiu do ar. E eu realmente queria manter ele, pois tudo está já configurado pra ele.
- Na página info.php (informações da compra) existe o botão imprimir boleto, que funciona perfeitamente.
- Aparentemente a success.phtml da GN é ignorada pelo magento.

Infelizmente eu não tenho muita experiência com módulos magento, mas tenho experiência com PHP e MySQL. Eu não sei como falar pro Magento usar a success.phtml de voces (ou porque ele nao usa). Liguei as mensagens de erros do server e não vi nada.

**EDIT1:** Todos meus testes foram no modo desenvolvedor.
**EDIT2:** Engraçado que eu alterei a info.phtml pra ficar `<strong>` o link de imprimir o boleto e mudou na hora, mas a success.phtml realmente não causa efeito (olhei no source e não tem nada da GN nela).

Cheers!
Gustavo

**Comment by tavinus** [comment]
Olá de novo, desculpa o double-post mas já tinha editado muito a mensagem anterior.

Eu desliguei o Inovarti one step checkout e nada mudou. Continua não usando a success.phtml de vocês. Também tentei modificar o arquivo gerencianet_transparent.xml mas não tive sucesso em fazer carregar. Tentei até usar o arquivo do Boleto Antigo que exibia o link no checkout como base, mas também nada. Voltei o original.

Chequei nomes de pastas e arquivos e tudo bate, incluindo letras maiusculas. Se ao menos eu tivesse alguma mensagem de erro pra me ajudar. Só falta eu ter esse botão na success pra abrir minha loja pra testes reais.

Idéias de como debugar?

Cheers!
Gustavo

**EDIT:** O arquivo `gerencianet_transparent.xml` é totalmente ignorado. Eu mudei o nome do arquivo e fiz uma venda teste com boleto e não recebi nenhuma mensagem de erro. Gerou a venda e o boleto sem problemas, mas nada de botão de imprimir obviamente. Também mudei o arquivo config.xml, onde referencia o `gerencianet_transparent.xml` (pra outro nome de arquivo inexistente) e de novo nada aconteceu. Só fiz esse teste pra ver se o arquivo chega a ser chamado, mas aparentemente nem isso. Não sei se o problema estaria no config.xml (aparentemente é o único lugar a se pensar no momento). O log da GN só mostra os dados dos boletos gerados e mais nada. Os logs de sistema não tem nada relacionado à GN.

**EDIT:** Só pra constar, eu enviei o zip pro server e dei unzip via ssh, depois instalei com cp -aiv. Isso já minimiza bastante a chance de ter algo corrompido também.

**Comment by magnored** [comment]
ja tentei de tudo tbm gustavo

**Comment by tavinus** [comment]
Ok, ACHO que descobri a origem do meu problema.

Eu tinha um módulo de boletos antigo instalado (MageBR Boleto Bancário) e aparentemente estes módulos conflitam entre si. Depois de desinstalar totalmente o módulo antigo, os botões de impressão apareceram na success e info. Infelizmente agora estou com um problema totalmente bizarro em que qualquer pedido de qualquer cliente é finalizado com o endereço (e nome) do meu usuário. Estamos tentando debugar, pode ser template, xml ou mesmo os pedidos testes que foram excluídos. Poderia ser que os dados de endereço do cliente tem algo inválido e a gerencianet rejeita o endereço? Só estou usando boleto bancário da GN e tenho CPF/CNPJ como obrigatório (nascimento obrigatório causa problemas no cadastro de pessoa juridica e não pretendo vender por cartoes usando a GN no momento). É realmente muuuito estranho esse bug agora. Usar o nome e endereço de um cliente para outro é um erro que beira o absurdo, não faz sentido.

EDIT: Faltou também dizer que tenho o endereço com 4 campos (mas nao achei como checar se os 4 estao na ordem descrita no Readme).

Bom, espero que te ajude @magnored. Veja se tem algum módulo conflitante. Pior que aqui desabilitar o módulo não ajudou, tivemos que deletar tudo mesmo.

**Comment by ceciliadeveza** [comment]
Prezado @tavinus , 

Testamos a utilização do módulo junto com o MageBR e conseguimos simular o erro. Esse módulo sobrescreve a página de sucesso da Gerencianet. O problema está no trecho:

```
<layout>
    <updates>
        <BoletoBancario>
            <file>BoletoBancario.xml</file>
        </BoletoBancario>
    </updates>
</layout>
```

No arquivo `app/code/community/MageBR/BoletoBancario/etc/config.xml`. Retirando esse trecho o botão do boleto é exibido.

@magnored , o Sr. pode verificar se possui instalado algum módulo com trecho semelhante a este?

**Comment by magnored** [comment]
@ceciliadeveza muito obrigado "senhora" uhehuaeuhaeuhea
deu certo!!...era isso mesmo

**Comment by tavinus** [comment]
Foi mais difícil do que parece achar o conflito.

O rapaz que desinstalou o módulo do MageBR não tinha removido todas as pastas e arquivos deles e depois que eu removi TUDO também consertou esse erro bizarro de ele exibir os pedidos com o meu usuário e endereço.

Veja bem, eu inspecionei o BD e as sales_orders estavam com os dados corretos, mas quando eu abria o pedido tanto no front-end quanto back-end os dados de envio e cobrança usavam os dados de outro usuário (o meu no caso).

Então eu recomendo que o @magnored verifique se os pedidos da loja dele estão saindo com os dados de entrega e cobrança corretos, sendo necessario comprar com 2 usuarios diferentes pra testar isso (até eu testar com outro usuario o endereço era o meu, que era correto).

Por fim, talvez só mudar ou desativar o arquivo mencionado pela @ceciliadeveza não seja suficiente. Recomendo remover totalmente o módulo do MageBR.

~~Agora só preciso resolver o problema de ter o link para o boleto sendo exibido mesmo quanto a venda não é via boleto (mesmo com o gerencianet + boleto desativados em formas de pagamento).~~

**EDIT:** Se precisar da estrutura do Módulo do MageBR pra desinstalar, coloquei ela aqui:
https://gist.github.com/tavinus/73c4168ae44c2cbe9688

**EDIT2:** Tá tudo certo agora. Testei tudo de novo gerando novas compras depois de limpar as caches e todas as páginas carregam legal. O botao de boleto só aparece quando é boleto mesmo, já até editei o css pra ficar como quero. Cheers! Valeu!

**Comment by ceciliadeveza** [comment]
Bacana @tavinus e @magnored. :)

Vou fechar a issue, qualquer problema estamos à disposição.
