### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by tavinus** [gerencianet/magento-dev#12]
Olá,

Existe alguma restrição sobre updates? Por exemplo, eu tenho uma versão mais antiga instalada (umas 4 revisões atrás). É seguro fazer update direto para a mais recente?

**Comment by jpferreira123** [comment]
Olá @tavinus , tudo bem?

Não existe restrições sobre update. Você pode realizar a atualização via upload ou utilizando o modgit que ambos irão atualizar todos os arquivos e o módulo continuará funcionando normalmente. Caso você tenha uma cópia da sua loja em ambiente de teste, recomendamos realizar a atualização nesse ambiente primeiramente antes de subir para produção.
Caso tenha alguma dúvida, adicione no skype: joao.ferreira.gerencianet

Abraço!
