### ISSUE TITLE
Cartão Aura

### ISSUE THREAD

**Issue by luizwbr** [gerencianet/magento-dev#13]
Estamos testando o cartão Aura, mas a api no checkout não permite que o número seja adicionado, já que os números de cartão Aura são maiores que o padrão, por ex.: 5078601912345600019.
![cartao_aura](https://cloud.githubusercontent.com/assets/308603/18363690/8737a7dc-75e1-11e6-805b-9fd84532cbd5.png)

A validação para o cartão existe, mas ela não está sendo chamada.

**Comment by chuckbnorris** [comment]
@luizwbr 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Atualmente, nosso módulo para Magento encontra-se na versão 0.2.6, e muitos erros foram corrigidos. Até então, não houveram relatos de outros usuários do módulo com relação a esta situação. Seria interessante se você testasse essa versão e confirmasse. Veja em nossa documentação oficial: https://dev.gerencianet.com.br/docs/magento

Caso enfrente qualquer tipo de problema ou situação atípica, e por envolver requisições da API que estão presentes em sua conta Gerencianet, o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre Magento/Módulo/API. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do Magento, print da tela de configurações do módulo, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição para ajudar no que for necessário.
