### ISSUE TITLE
Problema Cron

### ISSUE THREAD

**Issue by cfgalvani** [gerencianet/magento-dev#14]
Instalei o módulo da GerenciaNet para Magento e comecei a receber este erro por email do Cron:

`Catchable fatal error: Object of class Aoe_Scheduler_Model_Schedule could not be converted to string in /home/USER/public_html/app/code/local/Gerencianet/Transparent/Model/Mysql4/Notifications.php on line 30
`

A tarefa gerencianet_transparent_updater está sendo executada com erro..

**Comment by chuckbnorris** [comment]
@cfgalvani 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Lembro que em outro momento já havíamos interagido por ticket e telefone, se lembra? Me recordo que o problema já havia sido solucionado, pode me confirmar por gentileza?

Caso esteja enfrentando qualquer problema, por favor, me avise. Por envolver requisições da API que estão presentes em sua conta Gerencianet, o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir conosco. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre Magento/Módulo/API.

Qualquer coisa, estou à disposição para ajudar em tudo o que for necessário.
