### ISSUE TITLE
Pedido não finaliza

### ISSUE THREAD

**Issue by cfgalvani** [gerencianet/magento-dev#16]
Somente alguns pedidos não finalizam na loja de uma cliente. Uso o OSC6 Brasil. Você clica no botão de finalizar pedido e ele fica pensando um tempão e, do nada, para sem exibir nenhuma mensagem de erro. Na terceira tentativa ele apresenta o erro:

"Não é possível emitir três emissões idênticas. Por favor, entre em contato com nosso suporte para orientações sobre o uso correto dos serviços Gerencianet."

Vou abrir um ticket mas se alguém souber e puder ir me ajudando, agradeço.

**Comment by vissoci** [comment]
Realmente alguns problemas voltaram. O @jpferreira123  é quem me salvava, mas parece que saiu da Gerencianet. Me pediram para abrir um ticket, se demorar vou remover a solução. Está cansativo isso. Com o João as coisas andavam bem.

@franciscotfmc  @ceciliadeveza  Salvem a gente aí!!!!

**Comment by FilipeMata** [comment]
Olá @cfgalvani e @apzeiro  ,
Sei que a issue é um pouco antiga, mas peço que vocês enviem um ticket de suporte através de sua conta Gerencianet. 
Atualmente o nosso canal oficial de atendimento é através de ticket de suporte. Por lá conseguimos obter informações mais detalhadas a respeito de um problema.
Primeiramente nossa equipe de suporte técnico irá simular a mesma situação que o cliente passou. Caso algum bug seja de fato observado, uma solicitação de reparo do módulo será repassada para o setor responsável pelo desenvolvimento dos módulos.
Desta forma teremos um atendimento mais padronizado e que irá disponibilizar ao cliente um número de protocolo, que é o próprio número do ticket.
Portanto, em caso de dúvidas, estaremos a disposição para analisar sua demanda através do ticket de suporte.

**Comment by vissoci** [comment]
Infelizmente essa "interação via ticket" deixou muito a desejar. Não fluiu bem. Resolvi remover a solução da loja do cliente.
Posso afirmar que depois de muito tentar a Gerencianet beirou ser a melhor solução para lojas virtuais Magento, mas pecou no final. Na época que o João atendia via skype a coisa andou bastante rápido, mas agora com esse negócio de ticket o processo virou uma verdadeira carroça. 
Pense a respeito @FilipeMata . Isso não está funcionando bem. O Pessoal da Pagar.me está me dando um atendimento vip, muito parecido com o atendimento que o Joao (@jpferreira123) nos dava. 
Para eu não perder o cliente removi a Gerencianet.

Pensem a respeito.
