### ISSUE TITLE
Não é possível criar uma nova venda pelo admin

### ISSUE THREAD

**Issue by ygorlazaro** [gerencianet/magento-dev#17]
Entrando na gestão dos clientes dentro da Magento e adicionando um produto com um valor superior a cinco reais, eu recebo uma mensagem de erro dizendo "O valor mínimo para pagar com a Gerencianet é R$5,00.".

Depois de debuggar eu entendi que o problema acontece nesse trecho de código: https://github.com/gerencianet/gn-api-magento/blob/master/app/code/local/Gerencianet/Transparent/Model/Billet.php#L79

Essa variavel $quote é sempre nula quando utilizada esse método, criando uma nova compra pelo admin.

**Comment by ygorlazaro** [comment]
@infra-gerencianet @franciscotfmc @talitacampos @ceciliadeveza @thomazfeitoza @dannielhugo

**Comment by FilipeMata** [comment]
Olá @ygorlazaro ,
Peço que você envie um ticket de suporte através de sua conta Gerencianet. 
Atualmente o nosso canal oficial de atendimento é através de ticket de suporte. Por lá conseguimos obter informações mais detalhadas a respeito de um problema.
Portanto, peço que, além do código que você nos enviou aqui, envie também prints da tela de erro, de forma que consigamos entender com mais clareza o problema pelo qual você está passando. Primeiramente nossa equipe de suporte técnico irá simular a mesma situação que você passou. Caso algum bug seja de fato observado, uma solicitação de reparo do módulo será repassada para o setor responsável pelo desenvolvimento dos módulos.
Desta forma teremos um atendimento mais padronizado e que irá disponibilizar a você um número de protocolo, que é o próprio número do ticket.
Aguardaremos o seu ticket com todos os detalhes do seu problema.

**Comment by tavinus** [comment]
Né por nada não. Entendo que queiram o ticket, mas nem por isso precisam sempre copiar e colar a mesma resposta aqui. Também não tem porque ignorar um problema que talvez o cara já tenha dado até resposta, porque ele não abriu um ticket. Precisa rever esses métodos. Muita burocracia sem benefício algum...

**Comment by ygorlazaro** [comment]
@tavinus eu tentei pelo suporte e não consegui. Tentei consertar o componente por mim mesmo, mas fui acertando em tantos locais diferentes que no final desistimos da integração e fechamos com um concorrente, bem mais fácil de implementar.

Eu concordo com você, que se algo está disponível para a comunidade, em opensource, não é simplesmente abrir o código, mas ter a "comunidade" em si em torno do código. Mas é complexo de se fazer se a empresa só quiser trabalhar no GitHub porque "todo mundo lá está".

Desculpa se eu mesmo não puder lhe ajudar, caso você tenha passado por esse problema.
