### ISSUE TITLE
Módulo novo não funciona com multi-currency store onde a moeda base é outra que não BRL

### ISSUE THREAD

**Issue by alcorbrands** [gerencianet/magento-dev#18]
Minha loja tem moeda base USD, porém o módulo antigo (descontinuado) tratava a conversão na loja brasileira, ou seja, os clientes faziam os pagamentos em BRL conforme compravam.

Nem preciso informar que o módulo só estava disponível no BR.

Esse módulo novo não trata isso, ele exporta para o pagamento o preço base (em USD).

Ou seja, num produto base de USD 20 e preço na loja brasileira de BRL 60, ele exporta para pagamento 20.

Tentei modificar em /app/code/local/Gerencianet/Transparent/Model/Standard.php

De: getBasePrice();
Para: getPrice();

Ainda assim não deu certo...

Alguma dica?

**Comment by FilipeMata** [comment]
Bom dia @alcorbrands 

Percebemos que você já tinha aberto um ticket no nosso suporte com esta mesma dúvida. Sua dúvida foi respondia no ticket no dia 13/03/2017 às 08:18h.
Qualquer outra dúvida de integração deve ser tratada exclusivamente via ticket.
