### ISSUE TITLE
Pedido não aparece para cliente em front end

### ISSUE THREAD

**Issue by alexandresoaresramos** [gerencianet/magento-dev#19]
Como vai pessoal, estou com um problema que o pedido não ta aparecendo para o cliente após ele realizar a compra em nosso site. (vendo por boleto)
Achei que seria até eu faturar o pedido, mas mesmo assim não aparece, so aparecendo mesmo após eu registrar o envio com codigo de rastreamento.
Assim não dou credibilidade ao meu cliente, que paga ressabiado um boleto, e quando vai consultar o status do pedido dele não vê nada!

**Comment by chuckbnorris** [comment]
@alexandresoaresramos 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Por envolver requisições da API que estão presentes em sua conta Gerencianet, além de possuir informações pessoais (como dados cadastrais), o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre Magento/Módulo/API. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do Magento, print da tela de configurações do módulo, print da tela em seu Magento contendo a configuração dos status possíveis de pedidos, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição.
