### ISSUE TITLE
Carregando parcelas

### ISSUE THREAD

**Issue by giuliannosa** [gerencianet/magento-dev#2]
Na finalização fica "Carregando Parcelas" indefinidamente... Não aparece o número de parcelas. usando no CE 1.7.0.2

**Comment by ceciliadeveza** [comment]
Olá @giuliannosa, o Sr. está utilizando a versão mais recente do módulo?
Utiliza algum tipo de checkout diferente do padrão do Magento? Qual?

**Comment by giuliannosa** [comment]
Acabei de instalar a nova versão. Uso o IWD, mas o problema está no checkout nativo também, o "onepage". Criei uma nova aplicação no site da GN, coloquei no modo desenvolvedor e o mesmo problema até mesmo neste modo.

**Comment by mnoronha** [comment]
Estou com o mesmo problema, conseguiram solucionar?

**Comment by ceciliadeveza** [comment]
Prezados @giuliannosa e @mnoronha.

Acredito que o problema esteja relacionado com a versão do cURL configurado na máquina.

Para resolvê-lo, temos duas opções:
1. Atualizar a versão do cURL para a mais recente.
2. Baixar a lista de entidades certificadoras.

**Passo-a-passo para realizar o segundo procedimento:**
- Baixe a versão mais recente do módulo da Gerencianet, ou utilize 'modgit update' para atualiza-lo;
- Faça o download do 'cacert.pem' em http://curl.haxx.se/docs/caextract.html (copie e cole o texto todo em um arquivo chamado certificado.crt);
- Salve este arquivo na pasta raiz do seu Magento (no mesmo nível que as pastas app e lib)
- Teste o módulo novamente.

**Comment by giuliannosa** [comment]
Resolvido, se eu não utilizar SSL, com SSL ligado continua o Problema.

**Comment by vissoci** [comment]
@giuliannosa Atualize para a última versão que isso foi resolvido semana passada.
Aqui está funcionando bem.
