### ISSUE TITLE
magento 2.0

### ISSUE THREAD

**Issue by isacsg** [gerencianet/magento-dev#20]
Não tem integração com o magento 2 né?

**Comment by chuckbnorris** [comment]
@isacsg 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Neste momento, nosso módulo funciona na versão 1.7.x do Magento. Não garantimos ainda o pleno funcionamento na versão 2.x. Maiores detalhes estão disponíveis em nossa documentação: https://dev.gerencianet.com.br/docs/magento

Ademais, para que possamos documentar e registrar internamente sua sugestão de adequação do módulo, é ideal que você efetue login em sua conta Gerencianet e abra um ticket para relatar esta situação. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Qualquer coisa, estou à disposição.
