### ISSUE TITLE
Erro O e-mail informado não é válido

### ISSUE THREAD

**Issue by DiegoGermano** [gerencianet/magento-dev#21]
Olá Fiz a instalação do módulo segui as instruções de instalção, sobre permissões etc, quando finalizo a venda exibe a seguinte mensagem

![image](https://user-images.githubusercontent.com/2126205/26975323-aad604fe-4cf5-11e7-9c05-eec9330c68d9.png)

Poderia me ajudar por favor?

**Comment by chuckbnorris** [comment]
@DiegoGermano 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Por envolver requisições da API que estão presentes em sua conta Gerencianet, além de possuir informações pessoais (como dados cadastrais), o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre Magento/Módulo/API. Por aqui não é possível localizar seu cadastro conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do Magento, print da tela de configurações do módulo, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição.
