### ISSUE TITLE
Status do Pedido não é atualizado

### ISSUE THREAD

**Issue by DiegoGermano** [gerencianet/magento-dev#22]
Olá como faço para atualizar automaticamente o status do pedido no Magento? pedidos feito por boleto ficam em aberto e não são atualizados automaticamente.

Obrigado,
Abraço

**Comment by chuckbnorris** [comment]
@DiegoGermano 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Por padrão, os status são atualizados automaticamente sim, mas o que pode ocorrer é o seu servidor não estar recebendo os POSTs da Gerencianet por alguma razão (htaccess, alteração de diretório no seu FTP após instalação do módulo, firewall, dentre outras razões).

Dessa forma, por envolver requisições da API que estão presentes em sua conta Gerencianet, além de possuir informações pessoais (como dados cadastrais), o ideal é que você efetue login em sua conta Gerencianet e abra um ticket para interagir com o nosso suporte. Dessa forma, vamos conseguir verificar como as requisições estão sendo trabalhadas entre Magento/Módulo/API. Por aqui não é possível localizar seu cadastro conosco e visualizar todos esses detalhes.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Não esqueça de fornecer o máximo de informações no ticket, como por exemplo, versão do PHP, versão do Magento, print da tela de configurações do módulo, número da(s) transação(ões) envolvida(s) e demais informações que julgar pertinentes.

Qualquer coisa, estou à disposição.

**Comment by vissoci** [comment]
@DiegoGermano Conseguiu resolver o problema?
Está acontecendo o mesmo comigo.

**Comment by chuckbnorris** [comment]
@apzeiro 

Conforme issue #23 que você abriu, forneci as explicações detalhadas lá pra você. Confere lá por gentileza.
