### ISSUE TITLE
Retorno para a loja

### ISSUE THREAD

**Issue by vissoci** [gerencianet/magento-dev#23]
@tiagoxpl Queira por gentileza verificar o ticket Nº 899099. Não estou recebendo o retorno da gerencianet na loja.
Na gerencianet consta como pago, mas na loja fica como pagamento pendente.

**Comment by chuckbnorris** [comment]
@apzeiro 

Acessei o referido ticket e verifiquei sua mensagem. Verifiquei especificamente a transação que você se refere, mas também constatei outras situações que requerem sua atenção. Explicarei ambas para você.

Primeiramente, sobre a transação que menciona, observei que o envio da notificação por parte da Gerencianet ocorreu normalmente. Por questões de segurança, os prints que vou enviar aqui não contém nenhuma informação específica da transação ou de sua conta, mas para detalhes maiores, você mesmo pode conferir em API > Minhas Aplicações > Sua Aplicação, depois na aba "Produção", desça a barra de rolagem e veja a sub-aba "histórico de notificações", buscando por esta transação e vendo o status "Sucesso (200)". Clicando no ícone de um "olho" da última coluna você consegue visualizar os detalhes. Contudo, te enviamos esta notificação e seu servidor respondeu o seguinte (https://www.screencast.com/t/AzxO95yS). O conteúdo das notificações é apenas um "token de notificação", e neste caso, seu sistema recebeu este token e veio aqui consultar (veja na sub-aba "histórico de requisições") o conteúdo deste token (https://www.screencast.com/t/iaTtcBOC).

Quanto aos horários dessa atividade de "envio de notificação" e "leitura do conteúdo da notificação", enviamos em 25/02/2018 às 00:50:47 e seu sistema veio aqui consultar o conteúdo em 25/02/2018 às 00:50:47. Como pode notar, foi instantâneo. Então assim, o papel da Gerencianet foi realizado, mas não há como termos controle sobre o que sua plataforma irá fazer com o conteúdo da notificação que te enviarmos. É importante você verificar este erro que seu servidor está retornando e também as configurações de "Order Statuses" dentro do seu próprio Magento.

Agora, sobre a outra situação que encontrei em sua conta com as notificações. Existem outras transações que enviamos a notificação para você, porém, seu servidor nos retornou "Falha (503)". Esses códigos (503, 404, etc) são códigos de status HTTP - o que facilita a leitura/interpretação da razão para a referida falha.

Quanto ao erro 503 que seu servidor está retornando, em suma, significa que o serviço solicitado ao servidor não está disponível. Geralmente, o Apache apresenta tal erro quando não consegue atender a requisição em questão, e vários podem ser os motivos, entre eles:

- Excesso de requisições ao servidor, que se torna instável;
- Erro interno gerado por alguma configuração errônea;
- Falta de recursos disponíveis no servidor para atender a requisição;
- Dentre outros.

Para encontrar tais erros, o Apache fornece dois locais onde procurar pelos erros, o ErrorLog e AccessLog, em uma configuração padrão do apache, esses logs podem ser encontrados, respectivamente, em: /var/log/apache2/error.log e /var/log/apache2/access.log

Caso esteja trabalhando com mais de um host virtual em sua instalação, eles podem ou não estarem sendo gravados em locais distintos.

Inclusive, pode ser que esta situação tenha ocorrido em algum momento que você estava testando sua loja e ela estava desativada, enfim.

Espero ter esclarecido sua dúvida. Qualquer questão específica, pode interagir diretamente pelo ticket pelo ticket, tudo bem?

**Comment by vissoci** [comment]
Ok @tiagoxpl .
Mas o que fazer? O servidor está trabalhando com bastante folga. Não é máquina compartilhada é dedicada apenas à essa aplicação. Creio que não tenha relação com isso.

Penso ser algum problema com o módulo. Vou tentar reinstalar.
Esse problema é antigo, aliás o cliente deixou de usar a gerencianet ano passado por causa disso. Imaginei que tivesse sido resolvido mas pelo visto a issue #22 do é o mesmo problema que tenho.

Poderia me sugerir um caminho a fim de resolver o problema? Algum teste? Alguma sugestão?
Obrigado.

**Comment by chuckbnorris** [comment]
@apzeiro 

Então, é como mencionei anteriormente, veja no ErrorLog e AccessLog em seu servidor.

Problema no módulo em si não é, porque o envio do POST foi realizado, bem como sua plataforma recepcionou o token que foi enviado, a prova disso são as abas que citei.

Além disso, também vale a pena você verificar os logs do próprio Magento. No caso, o "[Error log record number](http://mariosam.com.br/magento/error-log/)" (geralmente em /var/report/) e o "[Log de eventos e exceções](http://mariosam.com.br/magento/error-log/)".

Outra possibilidade é que seu servidor tenha algum filtro no que tange a tratativa dos IPs de callback da Gerencianet. De repente, é preciso que você defina na white list os IPs da Gerencianet. Veja [nesta FAQ](https://gerencianet.com.br/artigo/quais-enderecos-de-ip-gerencianet-utiliza/) disponível em nosso site.

Essas são informações que podem nos auxiliar bastante.

**Comment by vissoci** [comment]
Infelizmente não localizei nada que denunciasse o problema.
A lista completa de IPs da GN está liberada no servidor.

Eu continuo suspeitando que seja erro no módulo. Não tenho outras anomalias com nenhum módulo. Desabilitei vários hoje para teste e o erro persiste.

Eu fiz o update via modgit, mas estava pensando em remover por completo e tentar instalar de novo.
Se não resolvermos essa questão o cliente fatalmente pedirá pra eu remover o módulo, como fez ano passado. Há um tempo essa integração vinha funcionando bem, mas justamente em função do surgimento desse erro que o cliente havia pedido para remover.

Não sei mais o que fazer. Entendo que essa seja a melhor solução de pgto, mas se não funcionar deixa a verificação trabalhosa. Veja o que vc pode fazer, por gentileza.

**Comment by chuckbnorris** [comment]
@apzeiro 

Visando unificar os contatos, respondi tudo com detalhes para você no ticket 899099, peço por gentileza que confira e interaja por lá caso precise, ok?

À disposição.

**Comment by vissoci** [comment]
@tiagoxpl já respondi por lá. Só que eu penso que vocês poderia tratar o assunto por aqui, afinal o módulo é mantido nesse repositório. Como pode ter mais gente com o mesmo problema a discussão aberta seria saudável para evolução do módulo.

Outra questão que acho fundamental é que este é um canal entre a gerencianet e os técnicos. Lá no sistema de ticket quem tem acesso, na maioria das vezes, é o cliente e não a gente.
Muitas vezes eu tenho que incomodar o cliente porque preciso acessar com o usuário dele (e a validação por telefone atrapalha bastante) só para ver uma resposta técnica que poderia ser mais ágil por aqui.
Antigamente vocês nos atendiam por e-mail também. Pensem a respeito. Está faltando um canal de atendimento estritamente técnico.

**Comment by chuckbnorris** [comment]
@apzeiro 

Entendo seu ponto de vista, mas é por isso que disponibilizamos o recurso de "usuário secundário", em que o titular Gerencianet pode cadastrar você como um usuário secundário, sendo um "desenvolvedor" e tendo acesso apenas a questões técnicas, inclusive o ticket. Veja detalhes: https://gerencianet.com.br/artigo/usuarios-secundarios

Importante salientar que há dados e prints que contém tokens, informações pessoais das transações, etc. Imagino que você não queira ter essas informações expostas de forma pública, por isso, o ticket é um canal oficial de comunicação e atendimento, inclusive técnico, que é o atendimento que está sendo prestado a você.

**Comment by vissoci** [comment]
Mas é bem isso, vocês acham prático aquele sistema, mas não é. Eu entendo que o local correto para discussões técnicas seria justamente no repositório.
Outro problema é que eu já tenho dois usuários secundários de outros clientes e tive que rebolar pra conseguir isso. Tenho que usar e-mail e cpf diferente e quando pede confirmação via telefone, faço o que? 
Uma pena não darem ouvidos a quem está desse lado.
Nada prático isso tudo. Mas Ok, deixa como está, vamos ver até onde isso vai.

**Comment by chuckbnorris** [comment]
@apzeiro 

Estou passando para você como é o funcionamento hoje, apenas isso. Estamos sempre recebendo sugestões e isso é sempre muito bem vindo, @apzeiro. Se não estivéssemos ouvindo, não estaríamos registrando internamente todas essas sugestões que recebemos. Críticas construtivas nos motivam e fazem com que tenhamos o desejo de sempre evoluir, dia após dia.

Qualquer situações envolvendo nossa plataforma, como qualquer dúvida com procedimentos relacionados a usuários secundários, telefone, etc, nossa equipe de atendimento está pronta para te ajudar o mais rápido possível, como é de praxe. Oferecemos inúmeros canais de suporte: https://gerencianet.com.br/artigo/entrar-em-contato

Obrigado pela sugestão. Qualquer coisa, estamos à disposição.

**Comment by vissoci** [comment]
Depois de mais um ano voltei a testar e o problema persiste.
