### ISSUE TITLE
Erro de validação

### ISSUE THREAD

**Issue by pedrohenrique1986** [gerencianet/magento-dev#25]
Olá, estou usando o modulo Gerencianet junto com Pagseguro Ricardo Martins e Onestep checkout da Inovarti.

Acontece um erro na hora do modulo da Gerencianet a respeito das validações, campos obrigatorios.

Quando você clica em cima do nome para digitar, ele já faz a validação, e mostra erro em todo o checkout.

Alguem já passou por isso? Sabe arrumar?

**Comment by pallomabritoGN** [comment]
Olá @pedroohsolucoes ! Tudo bem? 
Recentemente liberamos algumas atualizações com melhorias e correções. Inclusive, o módulo agora é compatível com o OpenMage.
Recomendamos atualizar o módulo e verificar se o comportamento foi normalizado.
Vale lembrar que estamos abertos a feedbacks buscando melhorar as ferramentas oferecidas!
Você consegue acompanhar essas novidades através da nossa comunidade no [Discord](https://discord.gg/x4yKpfYcFr)
Ou através dos tickets de suporte! Dessa forma, você consegue dar seu feedback e tirar suas dúvidas de maneira mais fácil e rápida!
Para abrir um ticket basta [clicar aqui](https://sistema.gerencianet.com.br/tickets/criar/)!
Quaisquer dúvidas, estamos à disposição!
