### ISSUE TITLE
Não mostra Parcelas

### ISSUE THREAD

**Issue by jlromualdo** [gerencianet/magento-dev#26]
olá

estou tentando usar o gerencianet no magento 1.9.4.4
Php 7.3
já verifiquei as permissões dos arquivos

mas não mostra as parcela ao finalizar a compra, fica processando e não informa as opções de parcelamento 

e quando troco a opção de pagamento para o boleto a mesma coisa, apenas fica "processando" e nada acontece

estou usando apenas o gerencianet como meio de pagemento

**Comment by LuizSantos22** [comment]
@jlromualdo 
Estou com o mesmo problema. 
Você conseguiu resolver isso?

Aqui está aparecendo um monte de erros:

prototype.js:119 Uncaught TypeError: Cannot read property 'className' of null
    at Function.reset (validation.js:30)
    at checkout.js:149
    at Array.forEach (<anonymous>)
    at Array.each (prototype.js:119)
    at klass._checkRegionRequired (checkout.js:149)
    at klass.update (checkout.js:164)
    at klass.initialize (checkout.js:147)
    at new klass (prototype.js:6)
    at <anonymous>:3:32
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
(index):6 Uncaught SyntaxError: Unexpected token '<'
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
VM233:4 Uncaught TypeError: Cannot read property 'addEventListener' of null
    at <anonymous>:4:40
    at t.activateScript (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at t.run (rocket-loader.min.js:1)
    at rocket-loader.min.js:1
    at HTMLScriptElement.<anonymous> (rocket-loader.min.js:1)
977394:398 Uncaught Error: Mismatched anonymous define() module: function(a){var b,c=navigator.userAgent,d=/iphone/i.test(c),e=/chrome/i.test(c),f=/android/i.test(c);a.mask={definitions:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},autoclear:!0,dataName:"rawMaskFn",placeholder:"_"},a.fn.extend({caret:function(a,b){var c;if(0!==this.length&&!this.is(":hidden"))return"number"==typeof a?(b="number"==typeof b?b:a,this.each(function(){this.setSelectionRange?this.setSelectionRange(a,b):this.createTextRange&&(c=this.createTextRange(),c.collapse(!0),c.moveEnd("character",b),c.moveStart("character",a),c.select())})):(this[0].setSelectionRange?(a=this[0].selectionStart,b=this[0].selectionEnd):document.selection&&document.selection.createRange&&(c=document.selection.createRange(),a=0-c.duplicate().moveStart("character",-1e5),b=a+c.text.length),{begin:a,end:b})},unmask:function(){return this.trigger("unmask")},mask:function(c,g){var h,i,j,k,l,m,n,o;if(!c&&this.length>0){h=a(this[0]);var p=h.data(a.mask.dataName);return p?p():void 0}return g=a.extend({autoclear:a.mask.autoclear,placeholder:a.mask.placeholder,completed:null},g),i=a.mask.definitions,j=[],k=n=c.length,l=null,a.each(c.split(""),function(a,b){"?"==b?(n--,k=a):i[b]?(j.push(new RegExp(i[b])),null===l&&(l=j.length-1),k>a&&(m=j.length-1)):j.push(null)}),this.trigger("unmask").each(function(){function h(){if(g.completed){for(var a=l;m>=a;a++)if(j[a]&&C[a]===p(a))return;g.completed.call(B)}}function p(a){return g.placeholder.charAt(a<g.placeholder.length?a:0)}function q(a){for(;++a<n&&!j[a];);return a}function r(a){for(;--a>=0&&!j[a];);return a}function s(a,b){var c,d;if(!(0>a)){for(c=a,d=q(b);n>c;c++)if(j[c]){if(!(n>d&&j[c].test(C[d])))break;C[c]=C[d],C[d]=p(d),d=q(d)}z(),B.caret(Math.max(l,a))}}function t(a){var b,c,d,e;for(b=a,c=p(a);n>b;b++)if(j[b]){if(d=q(b),e=C[b],C[b]=c,!(n>d&&j[d].test(e)))break;c=e}}function u(){var a=B.val(),b=B.caret();if(o&&o.length&&o.length>a.length){for(A(!0);b.begin>0&&!j[b.begin-1];)b.begin--;if(0===b.begin)for(;b.begin<l&&!j[b.begin];)b.begin++;B.caret(b.begin,b.begin)}else{for(A(!0);b.begin<n&&!j[b.begin];)b.begin++;B.caret(b.begin,b.begin)}h()}function v(){A(),B.val()!=E&&B.change()}function w(a){if(!B.prop("readonly")){var b,c,e,f=a.which||a.keyCode;o=B.val(),8===f||46===f||d&&127===f?(b=B.caret(),c=b.begin,e=b.end,e-c===0&&(c=46!==f?r(c):e=q(c-1),e=46===f?q(e):e),y(c,e),s(c,e-1),a.preventDefault()):13===f?v.call(this,a):27===f&&(B.val(E),B.caret(0,A()),a.preventDefault())}}function x(b){if(!B.prop("readonly")){var c,d,e,g=b.which||b.keyCode,i=B.caret();if(!(b.ctrlKey||b.altKey||b.metaKey||32>g)&&g&&13!==g){if(i.end-i.begin!==0&&(y(i.begin,i.end),s(i.begin,i.end-1)),c=q(i.begin-1),n>c&&(d=String.fromCharCode(g),j[c].test(d))){if(t(c),C[c]=d,z(),e=q(c),f){var k=function(){a.proxy(a.fn.caret,B,e)()};setTimeout(k,0)}else B.caret(e);i.begin<=m&&h()}b.preventDefault()}}}function y(a,b){var c;for(c=a;b>c&&n>c;c++)j[c]&&(C[c]=p(c))}function z(){B.val(C.join(""))}function A(a){var b,c,d,e=B.val(),f=-1;for(b=0,d=0;n>b;b++)if(j[b]){for(C[b]=p(b);d++<e.length;)if(c=e.charAt(d-1),j[b].test(c)){C[b]=c,f=b;break}if(d>e.length){y(b+1,n);break}}else C[b]===e.charAt(d)&&d++,k>b&&(f=b);return a?z():k>f+1?g.autoclear||C.join("")===D?(B.val()&&B.val(""),y(0,n)):z():(z(),B.val(B.val().substring(0,f+1))),k?b:l}var B=a(this),C=a.map(c.split(""),function(a,b){return"?"!=a?i[a]?p(b):a:void 0}),D=C.join(""),E=B.val();B.data(a.mask.dataName,function(){return a.map(C,function(a,b){return j[b]&&a!=p(b)?a:null}).join("")}),B.one("unmask",function(){B.off(".mask").removeData(a.mask.dataName)}).on("focus.mask",function(){if(!B.prop("readonly")){clearTimeout(b);var a;E=B.val(),a=A(),b=setTimeout(function(){B.get(0)===document.activeElement&&(z(),a==c.replace("?","").length?B.caret(0,a):B.caret(a))},10)}}).on("blur.mask",v).on("keydown.mask",w).on("keypress.mask",x).on("input.mask paste.mask",function(){B.prop("readonly")||setTimeout(function(){var a=A(!0);B.caret(a),h()},0)}),e&&f&&B.off("input.mask").on("input.mask",u),A()})}})}
http://requirejs.org/docs/errors.html#mismatch
    at C (977394:398)
    at J (977394:398)
    at 977394:398
/index.php/gerencianet/payment/installments/:1 Failed to load resource: the server responded with a status of 500 ()

**Comment by jvoliveiraGN** [comment]
Oi @jlromualdo tudo bem? :)
O módulo disponibilizado atualmente para magento é compatível com versões do PHP até a 7.0. Conforme nossa [documentação](https://dev.gerencianet.com.br/docs/magento#section-1-requisitos).
Nossa equipe já está trabalhando na atualização desse módulo para melhorar a compatibilidade com versões mais recentes. Em breve disponibilizaremos uma atualização.

Oi @LuizSantos22 tudo bem? :)
A falha apresentada é referente ao javascript do módulo. Poderia verificar se os arquivos foram inseridos nas pastas corretas, por favor? Por favor nos informe também as versões utilizadas na sua instalação.

Lembrando, pessoal, que temos uma comunidade no Discord com mais de mil desenvolvedores e também com a equipe de suporte técnico da Gerencianet. Lá vocês conseguem tirar dúvidas mais rapidamente sobre todos os serviços oferecidos pela Gerencianet. Para participar é só [clicar aqui!](https://discord.gg/bHKhsj9WCj)

**Comment by LuizSantos22** [comment]
Oi, eu já comentei que parte do erro se dá devido à versão PHP. Os outros
erros, não sei o motivo, pois não aparece nada no log. Estou usando
OpenMage 1.9.4.13, que é uma fork do Magento 1.9.4.5 que é a ultima versão.

OpenMage é uma iniciativa OpenSource para manter os patches de segurança e
melhorias do Magento 1.9 já que a Adobe não dá mais suporte oficial.

Conversei com vosso atendimento que ficou de fazer os testes no OpenMage e
fazer as correções.

Aqui em caráter de sugestão, rogo que atualizem o módulo para que fique
compatível com as versões PHP 7.3, 7.4 e 8.0, pois a versão 7.0 já não tem
suporte oficial e está cheia de vulnerabilidades de segurança.

**Comment by LuizSantos22** [comment]
E sim, as pastas estão corretas. Eu as subi corretamente. Inclusive mais de
uma vez, uma por uma em formato zip.

**Comment by jvoliveiraGN** [comment]
>  Estou usando OpenMage 1.9.4.13

No caso a falha se dá por incompatibilidade com o OpenMage mesmo.
Tomamos conhecimento do OpenMage recentemente, e com isso estamos trabalhando para atualizar o módulo e manter a compatibilidade com as novas versões. Em breve traremos atualizações cobrindo os pontos citados.
Quaisquer dúvidas, estamos à disposição. 😄

**Comment by jlromualdo** [comment]
> @jlromualdo
> Estou com o mesmo problema.
> Você conseguiu resolver isso?
> 
> Aqui está aparecendo um monte de erros:
> 
> prototype.js:119 Uncaught TypeError: Cannot read property 'className' of null
> at Function.reset (validation.js:30)
> at checkout.js:149
> at Array.forEach ()
> at Array.each (prototype.js:119)
> at klass._checkRegionRequired (checkout.js:149) at klass.update (checkout.js:164) at klass.initialize (checkout.js:147) at new klass (prototype.js:6) at :3:32 at t.activateScript (rocket-loader.min.js:1) at rocket-loader.min.js:1 at t.run (rocket-loader.min.js:1) at rocket-loader.min.js:1 at HTMLScriptElement. (rocket-loader.min.js:1) (index):6 Uncaught SyntaxError: Unexpected token '<' at t.activateScript (rocket-loader.min.js:1) at rocket-loader.min.js:1 at t.run (rocket-loader.min.js:1) at rocket-loader.min.js:1 at HTMLScriptElement. (rocket-loader.min.js:1) VM233:4 Uncaught TypeError: Cannot read property 'addEventListener' of null at :4:40 at t.activateScript (rocket-loader.min.js:1) at rocket-loader.min.js:1 at t.run (rocket-loader.min.js:1) at rocket-loader.min.js:1 at HTMLScriptElement. (rocket-loader.min.js:1) 977394:398 Uncaught Error: Mismatched anonymous define() module: function(a){var b,c=navigator.userAgent,d=/iphone/i.test(c),e=/chrome/i.test(c),f=/android/i.test(c);a.mask={definitions:{9:"[0-9]",a:"[A-Za-z]","*":"[A-Za-z0-9]"},autoclear:!0,dataName:"rawMaskFn",placeholder:"_"},a.fn.extend({caret:function(a,b){var c;if(0!==this.length&&!this.is(":hidden"))return"number"==typeof a?(b="number"==typeof b?b:a,this.each(function(){this.setSelectionRange?this.setSelectionRange(a,b):this.createTextRange&&(c=this.createTextRange(),c.collapse(!0),c.moveEnd("character",b),c.moveStart("character",a),c.select())})):(this[0].setSelectionRange?(a=this[0].selectionStart,b=this[0].selectionEnd):document.selection&&document.selection.createRange&&(c=document.selection.createRange(),a=0-c.duplicate().moveStart("character",-1e5),b=a+c.text.length),{begin:a,end:b})},unmask:function(){return this.trigger("unmask")},mask:function(c,g){var h,i,j,k,l,m,n,o;if(!c&&this.length>0){h=a(this[0]);var p=h.data(a.mask.dataName);return p?p():void 0}return g=a.extend({autoclear:a.mask.autoclear,placeholder:a.mask.placeholder,completed:null},g),i=a.mask.definitions,j=[],k=n=c.length,l=null,a.each(c.split(""),function(a,b){"?"==b?(n--,k=a):i[b]?(j.push(new RegExp(i[b])),null===l&&(l=j.length-1),k>a&&(m=j.length-1)):j.push(null)}),this.trigger("unmask").each(function(){function h(){if(g.completed){for(var a=l;m>=a;a++)if(j[a]&&C[a]===p(a))return;g.completed.call(B)}}function p(a){return g.placeholder.charAt(a<g.placeholder.length?a:0)}function q(a){for(;++a<n&&!j[a];);return a}function r(a){for(;--a>=0&&!j[a];);return a}function s(a,b){var c,d;if(!(0>a)){for(c=a,d=q(b);n>c;c++)if(j[c]){if(!(n>d&&j[c].test(C[d])))break;C[c]=C[d],C[d]=p(d),d=q(d)}z(),B.caret(Math.max(l,a))}}function t(a){var b,c,d,e;for(b=a,c=p(a);n>b;b++)if(j[b]){if(d=q(b),e=C[b],C[b]=c,!(n>d&&j[d].test(e)))break;c=e}}function u(){var a=B.val(),b=B.caret();if(o&&o.length&&o.length>a.length){for(A(!0);b.begin>0&&!j[b.begin-1];)b.begin--;if(0===b.begin)for(;b.begin<l&&!j[b.begin];)b.begin++;B.caret(b.begin,b.begin)}else{for(A(!0);b.begin<n&&!j[b.begin];)b.begin++;B.caret(b.begin,b.begin)}h()}function v(){A(),B.val()!=E&&B.change()}function w(a){if(!B.prop("readonly")){var b,c,e,f=a.which||a.keyCode;o=B.val(),8===f||46===f||d&&127===f?(b=B.caret(),c=b.begin,e=b.end,e-c===0&&(c=46!==f?r(c):e=q(c-1),e=46===f?q(e):e),y(c,e),s(c,e-1),a.preventDefault()):13===f?v.call(this,a):27===f&&(B.val(E),B.caret(0,A()),a.preventDefault())}}function x(b){if(!B.prop("readonly")){var c,d,e,g=b.which||b.keyCode,i=B.caret();if(!(b.ctrlKey||b.altKey||b.metaKey||32>g)&&g&&13!==g){if(i.end-i.begin!==0&&(y(i.begin,i.end),s(i.begin,i.end-1)),c=q(i.begin-1),n>c&&(d=String.fromCharCode(g),j[c].test(d))){if(t(c),C[c]=d,z(),e=q(c),f){var k=function(){a.proxy(a.fn.caret,B,e)()};setTimeout(k,0)}else B.caret(e);i.begin<=m&&h()}b.preventDefault()}}}function y(a,b){var c;for(c=a;b>c&&n>c;c++)j[c]&&(C[c]=p(c))}function z(){B.val(C.join(""))}function A(a){var b,c,d,e=B.val(),f=-1;for(b=0,d=0;n>b;b++)if(j[b]){for(C[b]=p(b);d++<e.length;)if(c=e.charAt(d-1),j[b].test(c)){C[b]=c,f=b;break}if(d>e.length){y(b+1,n);break}}else C[b]===e.charAt(d)&&d++,k>b&&(f=b);return a?z():k>f+1?g.autoclear||C.join("")===D?(B.val()&&B.val(""),y(0,n)):z():(z(),B.val(B.val().substring(0,f+1))),k?b:l}var B=a(this),C=a.map(c.split(""),function(a,b){return"?"!=a?i[a]?p(b)🅰️void 0}),D=C.join(""),E=B.val();B.data(a.mask.dataName,function(){return a.map(C,function(a,b){return j[b]&&a!=p(b)?a:null}).join("")}),B.one("unmask",function(){B.off(".mask").removeData(a.mask.dataName)}).on("focus.mask",function(){if(!B.prop("readonly")){clearTimeout(b);var a;E=B.val(),a=A(),b=setTimeout(function(){B.get(0)===document.activeElement&&(z(),a==c.replace("?","").length?B.caret(0,a):B.caret(a))},10)}}).on("blur.mask",v).on("keydown.mask",w).on("keypress.mask",x).on("input.mask paste.mask",function(){B.prop("readonly")||setTimeout(function(){var a=A(!0);B.caret(a),h()},0)}),e&&f&&B.off("input.mask").on("input.mask",u),A()})}})}
> http://requirejs.org/docs/errors.html#mismatch
> at C (977394:398)
> at J (977394:398)
> at 977394:398
> /index.php/gerencianet/payment/installments/:1 Failed to load resource: the server responded with a status of 500 ()

olá,
Desculpa a demora na resposta,
Não consegui resolver o problema no Magento 1 
Atualmente estou usando o Woocommerce 
att

**Comment by pallomabritoGN** [comment]
Olá @jlromualdo! Tudo bem? 
Recentemente liberamos algumas atualizações com melhorias e correções. Inclusive, o módulo agora é compatível com o OpenMage.
Recomendamos atualizar o módulo e verificar se o comportamento foi normalizado.
Vale lembrar que estamos abertos a feedbacks buscando melhorar as ferramentas oferecidas!
Você consegue acompanhar essas novidades através da nossa comunidade no [Discord](https://discord.gg/x4yKpfYcFr)
Ou através dos tickets de suporte! Dessa forma, você consegue dar seu feedback e tirar suas dúvidas de maneira mais fácil e rápida!
Para abrir um ticket basta [clicar aqui](https://sistema.gerencianet.com.br/tickets/criar/)!
Quaisquer dúvidas, estamos à disposição!
