### ISSUE TITLE
Retorno automático

### ISSUE THREAD

**Issue by Forbiddeen** [gerencianet/magento-dev#3]
Olá Srs, 

Gostaria de saber se esse módulo precisa ser configura-lo o retorno automático no GERENCIANET, se sim, podemos me informar o endereço?

Obrigado.

**Comment by ceciliadeveza** [comment]
Prezado @Forbiddeen ,

O módulo já vem com o retorno configurado, dessa forma, sua plataforma já recebe todas as notificações de mudanças de status das cobranças de forma automática.

**Comment by tavinus** [comment]
Desculpa reativar o tópico, mas queria saber sobre cancelamento de vendas.

Se eu cancelar uma venda no Magento que foi feita no boleto da GN, eu preciso cancelar esse boleto? Ele cancela sozinho? Ou simplesmente deixa ele expirar depois de 3 dias?

Eu procurei o boleto gerado no meu site na pagina da GerenciaNet e só achei os boletos gerados pelo próprio site da GN (usamos na loja física), mas nada do boleto gerado no meu site. Os boletos gerados no meu site não aparecem no gerencianet.com.br mesmo ou ficam separados em outro local? Ou ele já não aparecia por eu ter cancelado a venda antes?
