### ISSUE TITLE
Desconto Boleto

### ISSUE THREAD

**Issue by giuliannosa** [gerencianet/magento-dev#4]
O GerenciaNet utilizarei apenas para pagamentos via Cartão de Crédito, tenho outro módulo Boleto Bancário com desconto que coloquei na guia Promoções do Magento. No checkout quando clico no outro módulo aparece o desconto, depois quando clico no da GN continua com desconto; não quero que isso aconteça, pois o desconto é apenas via Boleto. Isso acontece no "onepage" e em todos outros checkouts, testei no IWD e da Inovarti também.

**Comment by tavinus** [comment]
Acho que depois que você digitar os dados do cartão o valor será atualizado, desde que sua promoção esteja configurada corretamente, claro. É assim que funciona pra mim com o pagseguro (só atualiza depois de digitar os dados do cartão). Não precisa clicar em comprar, é AJAX, ele detecta que preencheu e busca os dados de parcelas e valores, atualizando o review depois.

Tem uns hacks que dá pra fazer pra forçar o update, mas sempre depende do seu checkout e tema, sendo difícil implementar uma solução universal.

**Comment by vissoci** [comment]
Eu uso OSC6 e tenho o mesmo problema. Mas como o @tavinus falou, depois que digita o cartão o desconto some também.
Seria mais legal se já sumisse imediatamente, mas do jeito que está funciona bem no final.

**Comment by Forbiddeen** [comment]
Estou com o mesmo problema. Ele não atualiza. Provavelmente é algo causado exclusivamente com o módulo GERENCIANET.

**Comment by chuckbnorris** [comment]
@giuliannosa 
@tavinus 
@apzeiro 
@Forbiddeen 

Pessoal, me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

Como está a questão relatada por vocês? Pergunto pois neste momento nosso módulo encontra-se na versão 0.3.0 e desde então, uma série de correções e melhorias foram aplicadas ([vide link](https://dev.gerencianet.com.br/docs/magento)). Tentei localmente e não consegui reproduzir este mesmo problema que vocês citaram.

Caso o problema permaneça, é desejável que vocês abram um ticket em nosso suporte e me informem por aqui o número do ticket. Digo isso porque quando um ticket é aberto, consigo visualizar no histórico de requisições como elas estão chegando aqui para nós (se o atributo "discount" está presente, se não está, enfim), tudo isso por aqui eu não consigo sequer visualizar ou localizar a conta de vocês conosco.

Caso precise de orientações sobre como abrir tickets, por favor, acesse: https://dev.gerencianet.com.br/docs/fale-conosco

Qualquer coisa, estou à disposição.
