### ISSUE TITLE
Parcela mínima

### ISSUE THREAD

**Issue by vissoci** [gerencianet/magento-dev#5]
Em alguns testes eu percebi que se o valor do pedido for muito, o dropdown das parcelas não carrega. 
Existe um valor mínimo para o pagamento via cartão?
Se houver, seria interessante aparecer esse aviso na hora do pagamento.

**Comment by vissoci** [comment]
Fiz mais uns testes aqui e percebi que só mostra o campo à partir de 5 reais.

**Comment by vissoci** [comment]
Com o boleto o erro é similar também:
Veja a saída quando escolho um valor baixo de R$5,00.

SAÍDA:
{
  "code": 3500034,
  "error": "validation_error",
  "error_description": "O valor total da cobrança deve ser maior ou igual a 500."
}

O erro apresentado para o cliente também é bizarro, Aparece em um alert da forma que está abaixo:
"O valor total da cobrança deve ser maior ou igual a 500".
O cliente da loja virtual não faz ideia que a mensagem está mal formatada. Seria interessante  formatarem essa mensagem de forma que apareça o valor em R$.

**Comment by tavinus** [comment]
Sim, o valor mínimo é mesmo 5 reais. 
Aparece como 500 porque os valores sao sempre tratados com 2 casas decimais (sem o numero e sem a virgula ou ponto). Isso é meio padrão no Magento até onde eu sei.

Aqui na minha instalação eu restringi direto no Magento o valor de 10 reais para o mínimo do pedido. Assim já aparece a notificação antes que o pedido seja fechado.

Use:

```
Sistema > Configurações > Vendas > Vendas
>> Valor Mínimo do Pedido (Setar SIM e o Valor).
```

Espero que te ajude.

EDIT: Talvez seu caso seja mais complicado pois acho que cada parcela não pode ser menos que 5 reais (eu só uso o boleto a vista do GN). Ex: R$30,00 em 5 x R$ 6,00 = OK mas 10 x R$ 3,00 = FALHA por ser menos de 5 reais por parcela. Na real não sei se é assim que funciona, mas é algo para ser verificado.

**Comment by vissoci** [comment]
Ele considera apenas o valor total mesmo. Daí restringe no parcelamento. O problema é só se tiver uma compra abaixo de R$5,00.

Eu já restringi no sistema em R$5,00, mas como, mas o cliente possui produtos baratos abaixo disso. Fazendo isso o carrinho fica preso, não vai pro checkout. Não é a melhor saída.

O correto seria eliminar a forma de pagamento caso o pedido fosse abaixo desse valor. Tipo uma regra de promoção, mas eu não consegui fazer isso e não achei na internet um exemplo.
A condição até dá para ser criada, mas a ação não.

A formatação da mensagem ajudaria um pouco. "500" não é lógico para o cliente. Tudo que aparece no frontend tem que ser feito pensando no cliente e não no programador.

**Comment by vissoci** [comment]
Resolvido no último update
