### ISSUE TITLE
Exigindo CPF para cadastros Pessoa Jurídica (CNPJ) e erro com Data de Nascimento

### ISSUE THREAD

**Issue by vissoci** [gerencianet/magento-dev#6]
Fiz um teste cadastrando um cliente PJ. Os problemas são vários:

1) Ao cadastrar dá erro na data de nascimento. Na Gerencianet é obrigatório a data de nascimento, mas no cadastro de Pessoa Jurídica não se usa isso (o magento oculta).
Para resolver o problema na hora (pois o cliente tava esprando) eu mudei para opcional e daí passou.

2) Quando o cliente foi tentar finalizar a compra deu um erro informando que o CPF era inválido!!!! Affff... Cansativo isso!

A solução foi pedir para o cliente marcar Pagamento via depósito que daí eu mandaria a cobrança no e-mail dele.
Resultado: Perdemos a venda!!!!

Tive que remover NOVAMENTE a gerencianet da loja. Não sei se vou conseguir usar. São meses apanhando. Sei lá, não custava testar essas coisas.

Se puderem dar uma atenção aqui, agradeceria. 
@av5tecnologia 
@ceciliadeveza 
@thomazfeitoza 
@dannielhugo 
@franciscotfmc 

Falta tão pouco pra esse módulo ficar funcional. Vale a pena o esforço. Vamos lá pessoal!!!

Ps.: Essa semana um cliente nosso (de um condomínio) deixou de emitir 1944 boletos pelo sistema de vocês porque o cadastro não importava corretamente. Emitimos direto pelo banco infelizmente.

Abraço.
Marcos

**Comment by vissoci** [comment]
Faltou a imagem do erro:

![erro cpf](https://cloud.githubusercontent.com/assets/11969850/14221742/a14b7632-f83f-11e5-8297-c355e8042ec6.jpg)

**Comment by tavinus** [comment]
Sinceramente eu não estou usando pagamento via cartão do GN no meu site, somente boletos. Mas ontem mesmo eu estava pensando em como faz pra pagar via cartão pra pessoa jurídica. Pois é certo que não tem CPF no cadastro do cliente, mas todas as operadoras de cartão pedem data de nascimento do titular do cartão para processar o pagamento. Isso aqui no módulo da GN, pagseguro ou qualquer outro que você testar.

Então da forma que eu entendo, teria de ter o cadastro do cliente (pessoa juridica) + o cadastro do pagador/cartao, com data de nascimento. O cliente vai na nota fiscal e o pagador na cobrança, algo assim? 

Se alguém puder dar uma luz se é isso mesmo e se tem alguma forma especial de fazer isso rodar, seria interessante.

**Comment by vissoci** [comment]
O erro ocorre também para pagamento via boleto.

**Comment by tavinus** [comment]
Postei sobre isso no lugar errado. Mas enfim, eles precisam checar se o Magento tem as opções de data de nascimento e CPF cadastradas e se não tiver, tem que adicionar no form de pagamento pro cliente preencher. Nem muda muita coisa na lógica do módulo, basta checar e mudar de onde pega os dados pra enviar a cobrança.

**Comment by chuckbnorris** [comment]
@apzeiro 
@tavinus 

Me chamo Tiago e sou da equipe de Consultoria Técnica em Integrações da Gerencianet.

O módulo Magento já oferece tais possibilidades, está disponível em nossa documentação: https://dev.gerencianet.com.br/docs/magento

No momento desta resposta, o módulo encontra-se na versão 0.3.0.

Qualquer coisa, estou à disposição.

**Comment by vissoci** [comment]
4 meses para responder. Está no padrão da gerencianet! Por isso removi a integração dos meus clientes. Se melhorasse o suporte especializado eu até pensaria em voltar a indicar.

**Comment by chuckbnorris** [comment]
@apzeiro 

Entendemos sua frustração, mas é importante deixar claro que o Github é o repositório utilizado pela Gerencianet para distribuir nossas SDKs e módulos, coletar insights e, apesar de possuir um espaço em que a comunidade pode interagir, este não deve ser confundido com um canal oficial de atendimento com o suporte da empresa. Possuímos sim equipe especializada em integrações com a API, porém, o atendimento precisa ser realizado por algum dos canais oficiais de comunicação.

A Gerencianet é comprometida em superar as expectativas de seus clientes. Por isso, como parte deste comprometimento, oferecemos uma equipe de atendimento e suporte técnico, assim como telefone 0800 e outros números de contato. É importante frisar que o atendimento possui horários (segunda a sexta-feira, das 08h00 às 18h00) e tempo hábil para que nossa equipe retorne.

Para maiores informações, acesse nosso site www.gerencianet.com.br e clique no menu superior Ajuda para conferir os meios de contato com a Gerencianet, ou acesse diretamente o link a seguir -> https://gerencianet.com.br/artigo/entrar-em-contato/

Confira a seguir os meios de contato oficiais com a Gerencianet:

1) Tickets: podem ser abertos mesmo sem ter uma conta Gerencianet, através do seguinte link: https://accounts.gerencianet.com.br/faqticket/novoTicket/pagamentos. Caso possua uma conta Gerencianet, basta efetuar login e clicar no botão Novo Ticket. Os tickets podem ser abertos a qualquer momento (24 horas, 7 dias por semana) e são recepcionados por nossa equipe de suporte e é respondido em até 1 (um) dia útil;

2) Chat On-line: disponível ao acessar nosso site www.gerencianet.com.br, a opção de chat está disponível no canto inferior esquerdo da página. O horário de atendimento no chat é de segunda à sexta-feira, de 09h00 às 12h00, e de 14h00 às 18h00;

3) Contatos telefônicos: disponíveis através de 3 (três) telefones - 0800 941 2343 (somente ligações originadas de telefone fixo), 4000 1234 (capitais e regiões metropolitanas) ou (11) 2394-2208 (São Paulo e região). No caso do telefone, devido às demandas que estão passíveis de ocorrer em alguns horários, situações como minutos a mais na linha podem surgir. Contudo, é importante frisar que, dentre todos os meios de contato oferecidos, independente da forma que foi realizado, nossa equipe está sempre pronta para atendê-lo e resolver quaisquer questões.

Precisa de ajuda? Fale conosco.
Não é cliente ainda? Pergunte assim mesmo, adoramos interagir, coletar ideias e/ou sugestões.

Permanecemos à disposição para o que for necessário. Conte conosco!

**Comment by vissoci** [comment]
Entendo suas razões, mas eu discordo no fato de que este canal não tenha sido oferecido como suporte direto aos programadores e integradores. Isso foi feito expressamente pela então equipe da Gerencianet, basta ler issues anteriores que isso fica claro. Tenho diversos e-mails trocados pedindo pra eu postar as soluções e dúvidas aqui.
Não só no github como no skype havia um atendimento sensacional. Considerando um módulo tão imaturo diante da complexidade de informações e dinheiro que ele lida, estavam corretíssimos em dar atendimento especializado por esses canais. Digo novamente ser uma pena que acabou e por isso removi a solução dos meus clientes e parei de indicar. Ou fazia isso ou quem perderia seria eu. Um dia sem poder fazer um único recebimento no e-commerce, do lado de quem precisa desse recebimento, parece uma eternidade.

**Comment by vissoci** [comment]
Voltei a fazer um teste com o módulo, mas parece que esse problema da data de nascimento não foi resolvido ainda. Temos clientes PJ que vinham comprando normalmente, mas ao habilitar a gerecianet eles são direcionados para o cadastro solicitando Data de Nascimento.

Não há como contornar isso?

**Comment by chuckbnorris** [comment]
@apzeiro 

Qual a versão exata do módulo Gerencianet que você está utilizando?

**Comment by vissoci** [comment]
@tiagoxpl eu dei um update via modgit hoje. Creio que seja a última. Será que deu algo errado no update? No admin consta "Versão do Módulo: v0.3.0". Posso verificar alguma coisa pra lhe informar?

**Comment by vissoci** [comment]
Desabilitei o cartão e deixei somente boleto. Daí tirei a obrigatoriedade da Data de Nascimento. Dessa forma consegui concluir uma compra como PJ. Se habilitar o cartão daí vai dar problema.
Seria legal se no módulo tivesse a opção para a pessoa digitar os dados, quando fosse Pessoa Jurídica, semelhante como foi feito módulo do PagSeguro. Veja a imagem abaixo como é o deles:

![dados-cartao-pagseguro-exemplo-2](https://user-images.githubusercontent.com/11969850/36693027-a75e1af4-1b18-11e8-8017-548a077eff95.jpg)

**Comment by chuckbnorris** [comment]
@apzeiro 

Visando unificar os contatos, respondi tudo com detalhes para você no ticket 899099, peço por gentileza que confira e interaja por lá caso precise, ok?

À disposição.
