### ISSUE TITLE
Cade o suporte Gerencianet?????

### ISSUE THREAD

**Issue by vissoci** [gerencianet/magento-dev#7]
Tenho 3 clientes parados por causa de erros na API de vocês.
Não respondem e-mail e via telefone ninguém resolve...

Podiam pelo menos dizer: não tem solução. Daí eu já tirava de todos os cliente partia pra algo que funcionasse. Só que fica nessa lenga lenga..
Tá complicado hein!!! Cansativo.

**Comment by tavinus** [comment]
Você abriu um ticket com eles? Pode demorar um dia e ter uma resposta ruim, mas ao menos tem resposta. Você está com problemas com cartão de crédito? Questão da pessoa jurídica? Não explicar o seu problema não ajuda.

**Comment by vissoci** [comment]
Sim @tavinus . Abri ticket, envio e-mail, ligo diversas vezes no 0800 deles, mas está devagar.
Hoje pela manhã me deram um retorno por e-mail dizendo que irão corrigir a API até dia 15/04.

Informaram também que, diferente do descrito, o módulo não é compatível completamente para venda para Pessoa Jurídica (CNPJ), mas que o boleto bancário será possível depois dessa correção.

**Comment by jpferreira123** [comment]
Olá @apzeiro . Já estamos trabalhando nas correções do módulo. Gostaria de um contato por e-mail com você para maiores detalhes sobre os problemas que você está enfrentando. Meu e-mail é joao.ferreira@gerencianet.com.br . Aguardo seu contato.

**Comment by tavinus** [comment]
Olhando como é feito no módulo do pagseguro não é tão difícil. Precisa fazer uma função pra ver se tem CPF disponível (pelo cadastro do Magento), se não tiver coloca um campo no form do cartão e/ou boleto pra pessoa preencher e aí usa esse. Basicamente é isso. Vamos aguardar pois também preciso disto.
**EDIT:** Era melhor eu ter postado isso na issue relacionada, mas já foi.

**Comment by jpferreira123** [comment]
@tavinus , obrigado pela sugestão. A atualização que corrige esses erros e permite os pagamentos com CNPJ em boleto e cartão já está em fase de testes e nos próximos dias será disponibilizada. Caso tenha mais alguma sugestão/correção ou tenha interesse em ajudar nos testes, me envie um e-mail: joao.ferreira@gerencianet.com.br.
