### ISSUE TITLE
Emissão do boleto para Pessoa Jurídica (Utilizando Checkout Venda Mais)

### ISSUE THREAD

**Issue by Forbiddeen** [gerencianet/magento-dev#8]
Olá Srs,

Boa tarde.

Encontrei um bug em seu sistema, o módulo não reconhece pedidos emitidos usando CNPJ, ele só concluí se realizamos o pedido com CPF.

Fiz um teste na mesma loja usando o pagseguro e deu certo, mesmo sem o CPF e usando APENAS o CNPJ, gerou sem falhas.

Preciso de uma solução para isso, principalmente remover a obrigatoriedade do cpf, já que muitos emitem usando CNPJ.

**Comment by tavinus** [comment]
Olá.
Qual versão você está usando? Eles postaram uma versão nova faz alguns dias justamente para aceitar pagamentos de pessoas jurídicas (entre outras coisas). Ainda não testei, vou instalar agora. Você já está usando essa versão mais nova?

**Comment by Forbiddeen** [comment]
Provavelmente não é essa versão Tavinus.

Irei instala-la e posto o resultado, obrigado pela observação.

**Comment by Forbiddeen** [comment]
Senhores,

Fiz a atualização como nosso amigo sugeriu e resolveu em partes.

Agora o sistema emite o boleto via CNPJ, porém o gerencianet não valida os campos. 

Se tiver algum erro no checkout, como telefone inválido ou cpf errado, ele fica emitindo pedido a cada tentativa de emissão de boleto.

Isso é um problema grave, pois o cadastro do cliente é feito e quando você tenta usar os dados que estão no formulário (parcialmente processado), retorna erro de dados já utilizado.

Enfim, corrijam isso. Vale a pena adaptar seu módulo para o VENDA MAIS, é um ótimo checkout e o mais completo atualmente.

**Comment by tavinus** [comment]
Estou meio confuso com sua descrição do problema. Acho que não entendi direito, tem como explicar mais detalhado pra eu tentar reproduzir aqui? Ele emite um novo pedido ao tentar re-imprimir o boleto?

Só pra constar, você limpou a cache geral e também de JS/CSS depois de atualizar o módulo, certo?

E você está usando boleto ou cartão? Ou testou em ambos?

**Comment by Forbiddeen** [comment]
Olá, 

A loja é a meiaemalha.com.br

Ele faz o seguinte, se eu errar alguma informação, ele 'gera' um cadastro e um pedido, porém esse pedido (no frontend) se diz não finalizado por divergencia de informação, porém o sistema emite o cadastro do pedido normalmente e pior... como realiza o cadastro do cliente, o cliente fica perdido.

Enfim, meu cliente já autorizou remover o gerenciarnet, e provavelmente vou tirar das outras lojas que administro.

Preciso de algo que permita a emissão de boletos por cnpj sem causar erro no checkout VENDA MAIS.

**Comment by jpferreira123** [comment]
Olá @Forbiddeen ,

Gostaria de entender melhor o problema que está ocorrendo com sua instalação do módulo para encontrarmos uma solução o mais rápido possível. Você poderia me adicionar no Skype: joao.ferreira.gerencianet ? Ou se preferir, pode abrir um ticket com sua conta Gerencianet para que eu possa analisar suas requisições e verificar onde está o problema em questão.

Aguardo seu retorno. Obrigado.

**Comment by tavinus** [comment]
Sinceramente eu nem conheço esse checkout Venda Mais. Mas já dei uma estudada razoável no código do módulo gerencianet. Se você olhar no Javascript deles, vai perceber que eles testam por diversos checkouts diferentes na hora de salvar a venda, mas acho que não tem esse venda mais implementado.

Talvez seu problema comece aí. Seria bem fácil implementar isso de qualquer forma. Só precisa descobrir a função que salva as vendas no Venda Mais (acho). Se você vende no boleto pra pessoa física, funciona normal?

Posso estar errado mas acho que é um bom local de partida pra investigar.

**Comment by tavinus** [comment]
Bom, testei aqui e tenho alguns comentários.

Tive que colocar a data de nascimento como opcional para poder cadastrar pessoa Jurídica. Deixar isso obrigatório causou um erro similar ao do @Forbiddeen, em que o cliente foi cadastrado, mas sem senha ou ter tido todo o form preenchido. Tive que deletar o cliente e recadastrar depois de colocar DOB opcional.

Precisa mesmo pedir nome e CPF de alguém que vai comprar via boleto como pessoa jurídica? Não vejo muito porquê, mas mesmo se for necessário precisa corrigir esse form. A razão social está sendo montada como nome de pessoa física (Razão social + Nome fantasia, como se fosse nome e sobrenome).

Além disso, os dados de Nome/CPF estão vindo como Razão Social + CNPJ. Melhor vir em branco pois assim está errado e confunde o usuário.

Depois de preencher Nome e CPF ele gerou o boleto. E no boleto só tem as infos da empresa (nada do meu nome ou CPF).

Acho que por enquanto é isso.
Funcionou sim, mas com ressalvas e a instrução que vocês dao de deixar DOB obrigatório quebra o cadastro de pessoa jurídica do magento.

EDIT: Na minha primeira tentativa de fechar a venda como pessoa Juridica eu só cliquei em Fechar (com nome e CPF errados pois estavam os dados da empresa). Nesse ponto recebi uma mensagem PopUp informando que era inválido e voltou ao checkout. Preenchi meus dados corretamente e foi normal. Então esse problema de fechar a venda e ficar negada ou cliente perdido nao tive. Cliente ficou perdido aqui quando fui cadastrar a pessoa juridica e tinha DOB obrigatorio.

**Comment by Forbiddeen** [comment]
Olá @jpferreira123 

Estou adicionando você no skype, acredito que mostrando na tela fica mais fácil simular o erro.

**Comment by Forbiddeen** [comment]
Alguma posição?

Meu cliente está vendendo bastante via BOLETO, está cobrando o boleto de vocês.

**Comment by vissoci** [comment]
@Forbiddeen Testa agora. Eles atualizaram e agora aparece a opção tanto de boleto como cartão para PJ.
Eu uso OSC6 e está funcionando bem.
