### ISSUE TITLE
Dúvida módulo magento

### ISSUE THREAD

**Issue by jpedroWide** [gerencianet/magento-dev#9]
Gostaria de saber se este módulo possui funcionalidades de Market Place, conforme o recurso do Gerência Net: https://docs.gerencianet.com.br/marketplace/introducao

**Comment by jpferreira123** [comment]
Olá @jpedroWide ,

O módulo da Gerencianet para o Magento ainda não possui o recurso de Market Place implementado.

Caso tenha mais alguma dúvida, estou à disposição.
